# Makefile for converting Sweave into pdf.

# Generic make file for LaTeX: requires GNU make
#
# This makefile provides three targets: tex, pdf and clean.
# The default is "pdf".
# To make a tex file type "make tex"
# To make a pdf file, type "make pdf" or simply "make".
# To remove all files generated by make, type "make clean".
#
# Rouben Rostmaian,  September 2002   
# Minor adjustments for Rnw Nicholas Lewin-koh,  March 2005
# Even more minor adjustments Andrew Robinson,  December 2005

wrapper = template.tex

.PHONY: pdf tex clean

pdf: template.pdf

template.pdf: template.tex
	( \
	\pdflatex $(wrapper); \
	\bibtex $(wrapper:.tex=); \
	\pdflatex $(wrapper); \
	\pdflatex $(wrapper); \
	while \grep -q "Rerun to" $(wrapper:.tex=.log); \
	do \
		\pdflatex $(wrapper); \
	done \
	)

clean:
	@\rm -f  *~ Rplots.ps Rplots.pdf *.eps \
	$(wrapper:.tex=.aux) \
	$(wrapper:.tex=.log) \
	$(wrapper:.tex=.out) \
	$(wrapper:.tex=.dvi) \
	$(wrapper:.tex=.pdf) \
	$(wrapper:.tex=.toc) \
	$(wrapper:.tex=.blg) \
	$(wrapper:.tex=.idx) \
	$(wrapper:.tex=.bbl) ;

